export const GET_AIRPORTS = 'GET_AIRPORTS';
export const GET_AIRPORTS_SUCCESS = 'GET_AIRPORTS_SUCCESS';
export const GET_AIRPORTS_FAILURE = 'GET_AIRPORTS_FAILURE';

export const GET_AVAILABLE_FLIGHTS = 'GET_AVAILABLE_FLIGHTS'
export const GET_AVAILABLE_FLIGHTS_SUCCESS = 'GET_AVAILABLE_FLIGHTS_SUCCESS';
export const GET_AVAILABLE_FLIGHTS_FAILURE = 'GET_AVAILABLE_FLIGHTS_FAILURE';
